### PR TITLE
Built code into src/dist folder

### PR DESCRIPTION
**Pull request by fadyham**
- Built code into src/dist folder
- Added a ppe app plan and web app
- fixed build errors from typescript upgrade

### CODE REVIEW

**Comment by fadyham** [comment]
As in copy it during build to the dist folder?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by behoyh** [comment]
Right, if possible. Will fix ../../ ing out to get them

**Comment by fadyham** [comment]
Also, should the dist folder be under src/ or a peer?

**Comment by behoyh** [comment]
This totally gets into nitpick territory, but I would say peer is preferable?

**Comment by fadyham** [comment]
> This totally gets into nitpick territory, but I would say peer is preferable?

I'll see what I can do

**Comment by fadyham** [comment]
To have the dist folder as a peer to src then I'll have to move the packages.json file up to the root of the enlistment as a peer to src as well.  Otherwise the code won't run saying "can't find module <name>" since the node_modules folder is under src

**Pull request merged**
